# Generated by Django 5.0 on 2024-04-27 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DressCode',
        ),
        migrations.DeleteModel(
            name='Hours',
        ),
        migrations.RemoveField(
            model_name='restaurant_menu',
            name='Menu',
        ),
        migrations.DeleteModel(
            name='Restaurant',
        ),
        migrations.DeleteModel(
            name='Restaurant_Menu',
        ),
    ]
