# Generated by Django 5.0 on 2024-04-27 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0004_hours_room_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hours',
            old_name='room_type',
            new_name='meal_type',
        ),
        migrations.RemoveField(
            model_name='hours',
            name='description',
        ),
        migrations.AddField(
            model_name='hours',
            name='endDate',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='hours',
            name='startDate',
            field=models.TimeField(null=True),
        ),
    ]
