# Generated by Django 5.0 on 2024-04-27 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0005_rename_room_type_hours_meal_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant_menu',
            name='Menu',
        ),
        migrations.AddField(
            model_name='restaurant_menu',
            name='menu_type',
            field=models.CharField(choices=[('Starters', 'Starters'), ('Mains', 'Mains'), ('Salads', 'Salads'), ('Beverage', 'Beverage'), ('Dessert', 'Dessert')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
