# Generated by Django 5.0 on 2024-04-28 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0006_remove_restaurant_menu_menu_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DressCode',
        ),
    ]
