# Generated by Django 5.0 on 2024-04-28 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0007_delete_dresscode'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Hours',
            new_name='Hour',
        ),
    ]
